name: RemoteWatch
options:
  bundleIdPrefix: icu.rayae
  deploymentTarget:
    iOS: "14.0"

targets:
  RemoteWatch:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: RemoteWatch
    info:
      path: RemoteWatch/Info.plist
      properties:
        CFBundleDisplayName: 哪吒哨兵
        CFBundleShortVersionString: "1.0.2"
        CFBundleVersion: "2"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        ITSAppUsesNonExemptEncryption: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: icu.rayae.remotewatch
        MARKETING_VERSION: "1.0.2"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_BITCODE: "NO"

schemes:
  RemoteWatch:
    build:
      targets:
        RemoteWatch: all
    run:
      config: Debug
    archive:
      config: Release
